### ISSUE TITLE
Expected event "Transfer" to be emitted, but isnt

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-smart-contracts#898] opened 2024-08-08 15:36 UTC
### Description

It appears some events are not emitted for the following tests within Axelargateway:

[should allow the operators to burn external tokens](https://github.com/axelarnetwork/axelar-cgp-solidity/blob/6c4167b2c7f191cb7f45fbc336929f818ea6e2e5/test/AxelarGateway.js#L1030)
[should allow the operators to burn external tokens even if the deposit address has ether](https://github.com/axelarnetwork/axelar-cgp-solidity/blob/6c4167b2c7f191cb7f45fbc336929f818ea6e2e5/test/AxelarGateway.js#L1084)
[should allow the operators to burn the external token multiple times from the same address](https://github.com/axelarnetwork/axelar-cgp-solidity/blob/6c4167b2c7f191cb7f45fbc336929f818ea6e2e5/test/AxelarGateway.js#L1142)
All fail with: `AssertionError: Expected event "Transfer" to be emitted, but it wasn't`

Sample Transaction Hashes for Tests:
should allow the operators to burn the external token multiple times from the same address: https://hashscan.io/testnet/transaction/1723125697.573982315
should allow the operators to burn external tokens: https://hashscan.io/testnet/transaction/1723125656.258025003

One of their partners faced similar issues, which was related to `selfdestruct`. Comment for reference: https://github.com/onflow/flow-evm-gateway/issues/404#issuecomment-2260946569

### Steps to reproduce

1. Look at the tests
2. See sample transaction
3. Observe Transfer event not emitted 

### Hedera network

testnet

### Version

v0.52

### Operating system

None

**Comment by acuarica** [comment] 2024-08-13 13:28
Hi @mgarbs, thanks for sending this. We managed to reproduce the error locally, and verify the error didn't happen on an Ethereum network, _e.g._, Sepolia. At the moment, the issue seems to boil down to contracts after `selfdestruct` still have bytecode attached.

We continue investigating the root cause of the issue.

**Comment by acuarica** [comment] 2024-08-13 23:35
After further investigation, we managed to find the root cause. The issue is how `selfdestruct` handles deletion within the same transaction. More details can be found in tracking issue https://github.com/hashgraph/hedera-services/issues/14835. We expect to have a fix for this soon.

**Closed** 2024-10-15 15:13 UTC
Labels: bug
