### ISSUE TITLE
INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE when calling transferFrom()

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-smart-contracts#128] opened 2022-11-09 08:21 UTC
### Description

I get a `CONTRACT_REVERT_EXECUTED` with `INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE` when I try to call a `token.transferFrom()` on a HTS NFT with custom fees

### Steps to reproduce

1. Create a Contract with a token.transferFrom()
2. Create a HTS NFT with custom fixed fees
3. Call the contract function with the HTS NFT

--------- Or ---------
1. Clone https://github.com/se7enarianelabs/HederaBug_INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE
2. Run node testWithFees.js (You will get the error)
3. Run node testWithoutFees.js (It will be successful)

### Hedera network

testnet

### Version

0.1.0

### Operating system

macOS

**Comment by natanasow** [comment] 2022-11-09 14:30
@se7enarianelabs Could you try to use `token.delegateTransferFrom` instead of `token.transferFrom`?

**Comment by georgi-l95** [comment] 2022-11-09 16:15
Also this error occurs, when signing with incorrect signer. Please, double check your signer.

**Comment by se7enarianelabs** [comment] 2022-11-10 10:42
@natanasow with a `token.delegateTransferFrom` it's working, but why?
Why does it work for `token.transferFrom` if the token does not have customer fees, but if it does you must use `token.delegateTransferFrom`?

**Comment by natanasow** [comment] 2022-11-16 07:56
@se7enarianelabs  I guess if there is a customer fee, the fee should be collected from the signer. In your case, you can not execute `transferFrom` for a token with fees, because the `msg.sender` is the contract address itself and doesn't have any tiny bars to be collected as a fee. In another case when you are executing `transferFrom` to a token without fees, there is no problem because the fee should not be collected and the zero balance of the contract will not throw an exception.

**Comment by se7enarianelabs** [comment] 2022-11-16 12:55
@natanasow 
But shouldn't the HBAR allowance be used to pay the fee in `transferFrom`?

**Comment by natanasow** [comment] 2022-11-16 13:48
@se7enarianelabs Yep, but the contract itself doesn't have any HBAR allowance. Also, is your repo up-to-date because there are no `testWithFees` and `testWithoutFees` in [your repo](https://github.com/se7enarianelabs/HederaBug_INVALID_FULL_PREFIX_SIGNATURE_FOR_PRECOMPILE)?

**Comment by se7enarianelabs** [comment] 2022-11-16 13:55
@natanasow 
I forgot to push these files. Now it should be okay. I gave the contract the needed HBAR approval

**Comment by stoqnkpL** [comment] 2022-12-01 12:23
Hey @se7enarianelabs, just wanted to let you know we've identified a possible issue causing this and we're currently working on a fix. We'll keep you updated.

**Comment by roshan-bisht-lab49** [comment] 2022-12-17 03:36
Hey guys just checking, any update on this issue.?

**Comment by stoqnkpL** [comment] 2022-12-17 08:58
> Hey guys just checking, any update on this issue.?

Hey, @roshan-bisht-lab49 this was fixed on the consensus-node side. Once a new image for services including the fix is available we'll let you know.

**Comment by georgi-l95** [comment] 2023-01-25 10:50
Hey @roshan-bisht-lab49, this issue is fixed and fix is live on testnet. We cannot reproduce it anymore. Please try and reopen the issue, if you encounter it again.

**Closed by georgi-l95** 2023-01-25 10:50 UTC
Labels: bug, HTS, P1, Limechain
