### ISSUE TITLE
HTS NFT is still not compatible with Metamask

### ISSUE THREAD

**Issue by yonac1** [hashgraph/hedera-smart-contracts#633] opened 2023-12-16 12:02 UTC
### Problem

HTS NFT is still not compatible with Metamask.  I'm trying to send an NFT through HTS to a Hedera Testnet Metamask wallet, but then the NFT shows it to me as a Token in the token list tab inside Metamask instead of under the "NFTs" Tab and it says in the MetaMask "No NFTs yet", what should I do in order to make them shown in the NFTs Tab. Should I create 2 solidity files for nft create one with ethers.js -> ERC721 and one -> the HTS I have now?
I already associated the token
<img width="405" alt="2023-12-14_-17 29 29" src="https://github.com/hashgraph/hedera-smart-contracts/assets/81573021/8668f996-01f2-474a-9396-7ce42f3b61a0">
<img width="400" alt="2023-12-14_-17 31 11" src="https://github.com/hashgraph/hedera-smart-contracts/assets/81573021/06cd14f6-6604-47fd-9b7a-4c06ea79d10f">

### Solution

engineering team can prioritize it into our pipeline @ Pathorn on Discord

**Comment by ebadiere** [comment] 2024-01-10 20:15
Duplicate of #634

**Closed by ebadiere** 2024-01-10 20:15 UTC
Labels: enhancement
